In [22]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("../data/HU3_medicamentos_diabetes.xlsx")
df.shape

(1569, 32)

In [23]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
nregistro,1569.0,7.602104e+07,2.759623e+08,3.155600e+04,7.658700e+04,8.803000e+04,9.128400e+04,1.252000e+09
cn,1568.0,7.248901e+05,6.261735e+04,6.002210e+05,6.776678e+05,7.290610e+05,7.648212e+05,9.998530e+05
estado_aut,1569.0,1.459378e+12,2.856038e+11,-3.420612e+11,1.258585e+12,1.557266e+12,1.699009e+12,1.790187e+12
estado_rev,228.0,1.718252e+12,4.807024e+10,1.633453e+12,1.676474e+12,1.725194e+12,1.767871e+12,1.787906e+12
comercializado,1569.0,4.964946e-01,5.001471e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
requiere_receta,1569.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
generico,1569.0,7.654557e-01,4.238488e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
afecta_conduccion,1569.0,4.448693e-01,4.971098e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
triangulo_negro,1569.0,2.103250e-02,1.435384e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
medicamento_huerfano,1569.0,1.274697e-03,3.569152e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
biosimilar,1569.0,2.549395e-03,5.044320e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
num_registros_atc,1569.0,2.998725e+00,3.569152e-02,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
num_principios_activos,1569.0,1.135755e+00,3.426377e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00
num_excipientes,1569.0,2.033779e+00,1.183219e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,9.000000e+00
numero_tablas,1569.0,5.808795e+00,6.954051e+00,0.000000e+00,1.000000e+00,3.000000e+00,1.000000e+01,3.500000e+01
indicador_riesgo_severo,1569.0,1.277247e+01,6.913356e+00,1.000000e+00,8.000000e+00,1.200000e+01,1.700000e+01,3.800000e+01
Código Nacional,827.0,7.161334e+05,6.496970e+04,6.502920e+05,6.653895e+05,7.031750e+05,7.333395e+05,9.998530e+05
Precio de venta al público con IVA,827.0,2.029904e+01,2.318083e+01,9.500000e-01,4.170000e+00,1.118000e+01,2.793500e+01,1.334700e+02
Precio de referencia,686.0,1.344268e+01,1.302407e+01,9.500000e-01,3.870000e+00,8.340000e+00,1.997000e+01,1.012400e+02

In [24]:
df[(df['cn'].isnull()) & (~df['Código Nacional'].isnull())]

Empty DataFrame
Columns: [nregistro, nombre, pactivos, labtitular, labcomercializador, cn, dosis, forma_farmaceutica_simplificada, estado_aut, estado_rev, comercializado, requiere_receta, generico, afecta_conduccion, triangulo_negro, medicamento_huerfano, biosimilar, url_html_ficha_tecnica, url_foto_materiales, num_registros_atc, num_principios_activos, num_excipientes, vias_administracion, palabras_seccion_4_4, numero_tablas, indicador_riesgo_severo, Código Nacional, Estado, Precio de venta al público con IVA, Precio de referencia, Tratamiento de larga duración, Especial control médico]
Index: []

[0 rows x 32 columns]

In [25]:
df[(~df['cn'].isnull()) & (df['Código Nacional'].isnull())]
#hemos decidido que vamos a quitarnos todos los medicamentos cuyo cn tiene codigo nacional null porque no tienen precio de venta y entonces hemos decidido que no nos interesa

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
3,2230003,ACTRAPID 100 UI/ML SOLUCION INYECTABLE EN UN VIAL,INSULINA SOLUBLE NEUTRA,Novo Nordisk A/S,Novo Nordisk Pharma S.A.,775502.0,100 U/ml,INYECTABLE,1060034400000,NaN,...,"VÍA INTRAVENOSA, VÍA SUBCUTÁNEA",772,1,2,NaN,NaN,NaN,NaN,NaN,NaN
4,89508,BIGETRA 110 MG CAPSULAS DURAS EFG,DABIGATRAN ETEXILATO MESILATO,Adamed Laboratorios S.L.U.,Adamed Laboratorios S.L.U.,764777.0,110 mg,CAPSULA,1713779047000,1.785998e+12,...,VÍA ORAL,2885,30,14,NaN,NaN,NaN,NaN,NaN,NaN
11,61470,CAPTOPRIL NORMON 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Normon S.A.,Laboratorios Normon S.A.,649459.0,Captopril 25 mg,COMPRIMIDO,862437600000,NaN,...,VÍA ORAL,2404,1,6,NaN,NaN,NaN,NaN,NaN,NaN
13,61572,CAPTOPRIL STADA 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorio Stada S.L.,Laboratorio Stada S.L.,600221.0,25 mg,COMPRIMIDO,873064800000,1.707916e+12,...,VÍA ORAL,1707,2,3,NaN,NaN,NaN,NaN,NaN,NaN
20,64971,COZAAR 100 mg COMPRIMIDOS RECUBIERTOS CON PELI...,LOSARTAN POTASICO,Organon Salud S.L.,Organon Salud S.L.,809186.0,100 mg losartan potasico,COMPRIMIDO,1028757600000,NaN,...,VÍA ORAL,1176,1,11,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1561,89607,XARIVA 20 MG CAPSULAS DURAS EFG,RIVAROXABAN,Kern Pharma S.L.,Kern Pharma S.L.,765038.0,20 mg,CAPSULA,1716986221000,NaN,...,VÍA ORAL,1727,14,21,NaN,NaN,NaN,NaN,NaN,NaN
1562,7382018,XELEVIA 100 MG COMPRIMIDOS RECUBIERTOS CON PEL...,SITAGLIPTINA,Merck Sharp & Dohme B.V.,Merck Sharp & Dohme De Espana S.A.,602940.0,100 mg,COMPRIMIDO,1208728800000,NaN,...,VÍA ORAL,450,3,18,NaN,NaN,NaN,NaN,NaN,NaN
1563,114947003,"XULTOPHY 100 U/ML + 3,6 MG/ML SOLUCION INYECTABLE","LIRAGLUTIDA, INSULINA DEGLUDEC",Novo Nordisk A/S,Novo Nordisk Pharma S.A.,704321.0,"100 unidades/ 3,6 mg por ml",INYECTABLE,1416870000000,NaN,...,VÍA SUBCUTÁNEA,1156,8,19,NaN,NaN,NaN,NaN,NaN,NaN
1564,89973,ZEDILARF 10 MG COMPRIMIDOS RECUBIERTOS CON PEL...,DAPAGLIFLOZINA PROPANODIOL MONOHIDRATO,Pharmapath S.A.,Pharmapath S.A.,766348.0,10 mg,COMPRIMIDO,1732536796000,NaN,...,VÍA ORAL,1146,10,36,NaN,NaN,NaN,NaN,NaN,NaN
1565,89974,ZEDILARF 5 MG COMPRIMIDOS RECUBIERTOS CON PELÍ...,DAPAGLIFLOZINA PROPANODIOL MONOHIDRATO,Pharmapath S.A.,Pharmapath S.A.,766349.0,5 mg,COMPRIMIDO,1732536795000,NaN,...,VÍA ORAL,1146,10,36,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df[(df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
2,2230011,ACTRAPID INNOLET 100 UI/ML SOLUCION INYECTABLE...,INSULINA SOLUBLE NEUTRA,Novo Nordisk A/S,Novo Nordisk Pharma S.A.,775536.0,100 U/ml,INYECTABLE,973465200000,NaN,...,"VÍA INTRAVENOSA, VÍA SUBCUTÁNEA",772,1,2,775536.0,BAJA POR NO COMERCIALIZAR,35.89,NaN,SI,NO
6,111696003,BYDUREON 2 MG POLVO Y DISOLVENTE PARA SUSPENSI...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,703897.0,2 MG,INYECTABLE,1413756000000,1.767871e+12,...,VÍA SUBCUTÁNEA,829,7,11,703897.0,BAJA GENERAL,93.34,NaN,NO,NO
7,6362003,BYETTA 10 MICROGRAMOS SOLUCION INYECTABLE EN P...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,658304.0,"0,25 mg",INYECTABLE,1175637600000,1.767871e+12,...,VÍA SUBCUTÁNEA,712,2,8,658304.0,BAJA GENERAL,133.47,NaN,NO,NO
8,6362001,BYETTA 5 MICROGRAMOS SOLUCION INYECTABLE EN PL...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,658301.0,"0,25 mg",INYECTABLE,1175637600000,1.767871e+12,...,VÍA SUBCUTÁNEA,712,2,8,658301.0,BAJA GENERAL,66.74,NaN,NO,NO
36,1151051009,EBYMECT 5 MG/1.000 MG COMPRIMIDOS RECUBIERTOS ...,"DAPAGLIFLOZINA, METFORMINA HIDROCLORURO",Astrazeneca Ab,Laboratorio Tau S.A.,709156.0,5mg /1.000 mg,COMPRIMIDO,1449615600000,NaN,...,VÍA ORAL,1977,9,23,709156.0,ALTA,48.74,NaN,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1447,6366018,TANDEMACT 30 mg/2 mg COMPRIMIDOS,"PIOGLITAZONA, GLIMEPIRIDA",Cheplapharm Arzneimittel Gmbh,Laboratorios Rubio S.A.,663162.0,30 gm de pioglitazona + 2 mg de glimepirida,COMPRIMIDO,1254175200000,NaN,...,VÍA ORAL,25,1,10,663162.0,ALTA,56.46,NaN,NO,NO
1448,6366006,TANDEMACT 30 mg/4 mg COMPRIMIDOS,"PIOGLITAZONA, GLIMEPIRIDA",Cheplapharm Arzneimittel Gmbh,Laboratorios Rubio S.A.,663163.0,30 mg de pioglitazona + 4 mg de glimepirida,COMPRIMIDO,1254175200000,NaN,...,VÍA ORAL,1593,1,10,663163.0,ALTA,59.95,NaN,NO,NO
1497,114956002,"TRULICITY 0,75 mg SOLUCION INYECTABLE EN PLUMA...",DULAGLUTIDA,Eli Lilly Nederland B.V.,Lilly S.A.,704633.0,"0,75 mg",INYECTABLE,1418598000000,NaN,...,VÍA SUBCUTÁNEA,451,13,31,704633.0,ALTA,128.15,NaN,NO,NO
1498,114956007,"TRULICITY 1,5 mg SOLUCION INYECTABLE EN PLUMA ...",DULAGLUTIDA,Eli Lilly Nederland B.V.,Lilly S.A.,704632.0,"1,5 mg",INYECTABLE,1418598000000,NaN,...,VÍA SUBCUTÁNEA,451,13,31,704632.0,ALTA,128.15,NaN,NO,NO
1553,113843005,"VIPDOMET 12,5 MG/850 MG COMPRIMIDOS RECUBIERTO...","ALOGLIPTINA, METFORMINA HIDROCLORURO",Takeda Pharma A/S,Laboratorios Menarini S.A.,701205.0,"12,5 mg/850 mg",COMPRIMIDO,1389826800000,NaN,...,VÍA ORAL,1248,5,15,701205.0,ALTA,48.96,NaN,NO,NO

In [27]:
df[(~df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

#cargarnos precio de referencia porque hay algunos que son nulos y los que no son nulos son siempre iguales que el precio de venta al público con IVA. Por lo tanto, podemos eliminar la columna de precio de referencia.
#el precio de referencia nunca existe sin el de venta, y cuando existe es igual a él

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,70452,ACARBOSA TECNIGEN 100 mg COMPRIMIDOS,ACARBOSA,Tecnimede España Industria Farmaceutica S.A.,Tecnimede España Industria Farmaceutica S.A.,662260.0,100 mg,COMPRIMIDO,1233788400000,NaN,...,VÍA ORAL,149,1,2,662260.0,ALTA,15.30,15.30,SI,NO
1,70451,ACARBOSA TECNIGEN 50 mg COMPRIMIDOS,ACARBOSA,Tecnimede España Industria Farmaceutica S.A.,Tecnimede España Industria Farmaceutica S.A.,662258.0,50 mg,COMPRIMIDO,1233788400000,NaN,...,VÍA ORAL,149,1,2,662258.0,ALTA,7.65,7.65,SI,NO
5,89509,BIGETRA 150 MG CAPSULAS DURAS,DABIGATRAN ETEXILATO MESILATO,Adamed Laboratorios S.L.U.,Adamed Laboratorios S.L.U.,764780.0,150 mg,CAPSULA,1713779048000,1.785998e+12,...,VÍA ORAL,2813,25,12,764780.0,BAJA GENERAL,45.08,45.08,NO,NO
9,62304,CAPTOPRIL CINFA 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,706317.0,25 mg captopril,COMPRIMIDO,909874800000,NaN,...,VÍA ORAL,2475,1,8,706317.0,ALTA,3.53,3.53,SI,NO
10,62305,CAPTOPRIL CINFA 50 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,706341.0,50 mg captopril,COMPRIMIDO,909874800000,NaN,...,VÍA ORAL,2475,1,8,706341.0,ALTA,3.53,3.53,SI,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,90125,VILDAGLIPTINA/METFORMINA VIVANTA 50 MG/1 000 M...,"VILDAGLIPTINA, METFORMINA HIDROCLORURO",Vivanta Generics S.R.O.,Mabo Farma S.A.,766878.0,50 mg/1.000 mg,COMPRIMIDO,1764930254000,NaN,...,VÍA ORAL,1055,2,7,766878.0,ALTA,36.19,36.19,NO,NO
1548,90126,VILDAGLIPTINA/METFORMINA VIVANTA 50 MG/850 MG ...,"VILDAGLIPTINA, METFORMINA HIDROCLORURO",Vivanta Generics S.R.O.,Mabo Farma S.A.,766888.0,50 mg/850 mg,COMPRIMIDO,1764930254000,NaN,...,VÍA ORAL,1055,2,7,766888.0,ALTA,36.19,36.19,NO,NO
1566,59127,ZESTRIL 20 mg COMPRIMIDOS,LISINOPRIL,Atnahs Pharma Netherlands Bv.,Atnahs Pharma Netherlands Bv.,865287.0,20 mg lisinopril,COMPRIMIDO,678319200000,NaN,...,VÍA ORAL,2100,1,10,865287.0,ALTA,6.35,6.35,SI,NO
1567,8483009,ZOMARIST 50 mg/1000 mg COMPRIMIDOS RECUBIERTOS...,"METFORMINA HIDROCLORURO, VILDAGLIPTINA",Novartis Europharm Limited,Esteve Pharmaceuticals S.A.,662085.0,1000/50 mg/mg,COMPRIMIDO,1231455600000,NaN,...,VÍA ORAL,1054,2,7,662085.0,ALTA,36.19,36.19,NO,NO
1568,8483003,ZOMARIST 50 mg/850 mg COMPRIMIDOS RECUBIERTOS ...,"METFORMINA HIDROCLORURO, VILDAGLIPTINA",Novartis Europharm Limited,Esteve Pharmaceuticals S.A.,662084.0,850/50 mg/mg,COMPRIMIDO,1231455600000,NaN,...,VÍA ORAL,1054,2,7,662084.0,ALTA,36.19,36.19,NO,NO

In [28]:
#cargarnos precio de referencia porque hay algunos que son nulos y los que no son nulos son siempre iguales que el precio de venta al público con IVA. Por lo tanto, podemos eliminar la columna de precio de referencia.
#el precio de referencia nunca existe sin el de venta, y cuando existe es igual a él
df_clean = df.copy()
df_clean = df_clean.dropna(subset=["Código Nacional"])
print(df_clean.shape)

(827, 32)

In [29]:
df[(~df['Precio de referencia'].isnull()) & (df['Precio de venta al público con IVA'].isnull())]

Empty DataFrame
Columns: [nregistro, nombre, pactivos, labtitular, labcomercializador, cn, dosis, forma_farmaceutica_simplificada, estado_aut, estado_rev, comercializado, requiere_receta, generico, afecta_conduccion, triangulo_negro, medicamento_huerfano, biosimilar, url_html_ficha_tecnica, url_foto_materiales, num_registros_atc, num_principios_activos, num_excipientes, vias_administracion, palabras_seccion_4_4, numero_tablas, indicador_riesgo_severo, Código Nacional, Estado, Precio de venta al público con IVA, Precio de referencia, Tratamiento de larga duración, Especial control médico]
Index: []

[0 rows x 32 columns]

In [ ]:

df_clean = df_clean.drop(columns=["Precio de referencia"])

df[(~df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

In [31]:
df.describe(include='object').T
#vamos a mirar todas las columnas escritas para encontrar cosas a saltar

,count,unique,top,freq
nombre,1569,1525,LANTUS 100 UNIDADES/ML SOLUCION INYECTABLE EN ...,5
pactivos,1569,115,RIVAROXABAN,114
labtitular,1569,141,Laboratorios Cinfa S.A.,73
labcomercializador,1569,139,Teva Pharma S.L.U.,91
dosis,1569,249,5 mg,110
forma_farmaceutica_simplificada,1569,8,COMPRIMIDO,1302
url_html_ficha_tecnica,1569,1569,https://cima.aemps.es/cima/dochtml/ft/70452/FT...,1
url_foto_materiales,389,389,https://cima.aemps.es/cima/fotos/thumbnails/ma...,1
vias_administracion,1569,7,VÍA ORAL,1425
palabras_seccion_4_4,1569,611,450,19
Estado,827,4,ALTA,665
Tratamiento de larga duración,827,2,NO,551
Especial control médico,827,1,NO,827

In [32]:
df['Estado'].value_counts()

Estado
ALTA                           665
BAJA GENERAL                    99
BAJA POR NO COMERCIALIZAR       56
SUSPENSION TEMPORAL GENERAL      7
Name: count, dtype: int64

In [33]:
df['Especial control médico'].value_counts()

Especial control médico
NO    827
Name: count, dtype: int64

In [34]:
df['dosis'].value_counts()
#tenemos que limpiar los valores "sucios" para quitar las columnas unicas que no tienen sentido

dosis
5 mg                 110
50 mg                101
20 mg                 86
100 mg                70
15 mg                 65
                    ...
 100 mg                1
75 mg clopidogrel      1
75 mg clopidrogel      1
15mg-850mg             1
850/50 mg/mg           1
Name: count, Length: 249, dtype: int64

In [35]:
df['vias_administracion'].value_counts()

#podriamos unir las columnas VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA y VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA

vias_administracion
VÍA ORAL                                              1425
VÍA SUBCUTÁNEA                                         113
VÍA INTRAVENOSA, VÍA SUBCUTÁNEA                         11
VÍA SUBLINGUAL                                           9
VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA                        5
VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA       3
VÍA NASAL                                                3
Name: count, dtype: int64